with get_all as (
    select
        loan_system_id,
        borrower_system_id,
        user_system_id,
        registration_date,
        prequal_submission_date,
        qualified_date,
        event_timestamp,
        localized_event_date,
        event_name,
        group_status_name,
        unified_status_name,
        event_name as platform_status_name,
        event_user_type,
        event_user_name,
        event_user_role,
        opportunity_owner_name,
        referral_code,
        borrower_name,
        borrower_dob,
        borrower_pob,
        borrower_phone_number,
        borrower_email,
        borrower_marital_status,
        borrower_identity_number,
        borrower_gender,
        borrower_occupation,
        borrower_occupation_detail,
        borrower_verified_income,
        borrower_income_first_month,
        borrower_income_second_month,
        borrower_income_third_month,
        borrower_income_fourth_month,
        borrower_income_fifth_month,
        borrower_income_sixth_month,
        borrower_business_sector,
        borrower_business_address,
        borrower_verified_spouse_income,
        borrower_spouse_income_first_month,
        borrower_spouse_income_second_month,
        borrower_spouse_income_third_month,
        borrower_spouse_income_fourth_month,
        borrower_spouse_income_fifth_month,
        borrower_spouse_income_sixth_month,
        cast(null as int) as borrower_payment_bandwidth,
        loan_status,
        loan_dbr,
        loan_credit_overdue_status,
        loan_localized_disbursement_date,
        loan_localized_expected_mature_date,
        loan_due_date,
        loan_incentive_amount,
        loan_ltv_verified,
        loan_ltv as loan_ltv_self_declared,
        loan_dbr_verified,
        loan_self_declared_dbr,
        loan_dbr_status,
        loan_agreement_lender_platform_number,
        loan_agreement_borrower_lender_number,
        loan_requested_limit,
        loan_recommended_limit,
        loan_recommended_limit_after_survey,
        loan_limit,
        loan_interest,
        loan_tenure_months,
        loan_installment,
        first_purpose,
        second_purpose,
        third_purpose,
        property_localized_submission_date,
        property_estimated_price,
        property_verified_price,
        property_type,
        property_surface_area,
        property_building_area,
        property_certificate_type,
        property_certificate_owner,
        property_owner_presence_status,
        property_certificate_collateral_status,
        property_certificate_owner_presence_status,
        property_first_address,
        property_second_address,
        property_village_name,
        property_district_name,
        property_city_name,
        property_province_name,
        property_occupancy_status,
        property_occupants,
        criteria_active_from_timestamp,
        criteria_active_until_timestamp,
        opportunity_owner_email,
        opportunity_owner_role,
        'pijar' as business_platform
    from {{ ref('stage_histories_pijar') }}
    union all
    select
        heloc_id,
        borrower_system_id,
        user_system_id,
        registration_date,
        prequal_submission_date,
        qualified_date,
        status_timestamp,
        localized_status_date,
        status_name,
        group_status_name,
        unified_status_name,
        zh.status_name_zoho as platform_status_name,
        actor_type,
        actor_name,
        actor_role,
        cast(null as varchar) as opportunity_owner_name,
        cast(null as varchar) as referral_code,
        borrower_name,
        borrower_dob,
        cast(null as varchar) as borrower_pob,
        borrower_phone_number,
        borrower_email,
        borrower_marital_status,
        borrower_identity_number,
        borrower_gender,
        borrower_occupation,
        borrower_occupation_detail,
        borrower_income_first_month as borrower_verified_income,
        borrower_income_first_month,
        borrower_income_second_month,
        borrower_income_third_month,
        borrower_income_fourth_month,
        borrower_income_fifth_month,
        borrower_income_sixth_month,
        borrower_business_sector,
        borrower_business_address,
        borrower_spouse_income_first_month as borrower_verified_spouse_income,
        borrower_spouse_income_first_month,
        borrower_spouse_income_second_month,
        borrower_spouse_income_third_month,
        borrower_spouse_income_fourth_month,
        borrower_spouse_income_fifth_month,
        borrower_spouse_income_sixth_month,
        borrower_payment_bandwidth,
        loan_status,
        loan_dbr,
        loan_credit_overdue_status,
        loan_initial_disbursement_date,
        cast(null as date) as loan_localized_expected_mature_date,
        cast(null as date) as loan_due_date,
        cast(null as int) as loan_incentive_amount,
        loan_limit / property_verified_property_value as loan_ltv_verified,
        loan_requested_limit / property_estimated_price as loan_ltv_self_declared,
        cast(null as decimal(9, 2)) as loan_dbr_verified,
        cast(null as decimal(9, 2)) as loan_self_declared_dbr,
        loan_dbr_status,
        cast(null as varchar) as loan_agreement_lender_platform_number,
        cast(null as varchar) as loan_agreement_borrower_lender_number,
        loan_requested_limit,
        loan_recommended_limit,
        loan_recommended_limit as loan_recommended_limit_after_survey,
        loan_limit,
        loan_interest,
        loan_agreed_monthly_payment as loan_installment,
        loan_tenure,
        loan_purpose_main as first_purpose,
        cast(null as varchar) as second_purpose,
        cast(null as varchar) as third_purpose,
        property_submission_date,
        property_estimated_price,
        property_verified_property_value,
        property_type,
        property_surface_area,
        property_building_area,
        property_certificate_type,
        property_certificate_owner,
        property_owner_presence_status,
        property_certificate_collateral_status,
        property_certificate_owner_presence_status,
        property_first_address,
        property_second_address,
        property_village_name,
        property_district_name,
        property_city_name,
        property_province_name,
        cast(null as varchar) as property_occupancy_status,
        cast(null as varchar) as property_occupants,
        cast(null as timestamp) as criteria_active_from_timestamp,
        cast(null as timestamp) as criteria_active_until_timestamp,
        cast(null as varchar) as opportunity_owner_email,
        cast(null as varchar) as opportunity_owner_role,
        'infinid' as business_platform
    from {{ ref('stage_histories_infinid') }}
    left join {{ ref('dim_zoho_status') }} as zh on status_name = zh.event_name_infinid
),

is_migration as (
    select
        get_all.*,
        coalesce(mt.loan_id_pijar is not null, false) as is_migration
    from get_all
    left join {{ ref('migration_tracking') }} as mt on
        get_all.borrower_phone_number = mt.borrower_phone_number
        or get_all.borrower_email = mt.borrower_email
),

migrate_cohort as (
    select
        borrower_phone_number,
        min(prequal_submission_date) as prequal_submission_date,
        min(qualified_date) as qualified_date,
        min(registration_date) as registration_date
    from is_migration
    where is_migration = true
    group by 1
),

dedup_cohort as (
    select
        loan_system_id,
        borrower_system_id,
        user_system_id,
        case
            when is_migration = true then mc.registration_date
            else im.registration_date
        end as registration_date,
        case
            when is_migration = true then mc.prequal_submission_date
            else im.prequal_submission_date
        end as prequal_submission_date,
        case
            when is_migration = true then mc.qualified_date
            else im.qualified_date
        end as qualified_date,
        is_migration,
        event_timestamp,
        localized_event_date,
        event_name,
        group_status_name,
        --unified_status_name,
        platform_status_name,
        event_user_type,
        event_user_name,
        event_user_role,
        opportunity_owner_name,
        borrower_name,
        borrower_dob,
        borrower_pob,
        im.borrower_phone_number,
        borrower_email,
        borrower_marital_status,
        borrower_identity_number,
        borrower_gender,
        borrower_occupation,
        borrower_occupation_detail,
        borrower_verified_income,
        borrower_income_first_month,
        borrower_income_second_month,
        borrower_income_third_month,
        borrower_income_fourth_month,
        borrower_income_fifth_month,
        borrower_income_sixth_month,
        borrower_business_sector,
        borrower_business_address,
        borrower_verified_spouse_income,
        borrower_spouse_income_first_month,
        borrower_spouse_income_second_month,
        borrower_spouse_income_third_month,
        borrower_spouse_income_fourth_month,
        borrower_spouse_income_fifth_month,
        borrower_spouse_income_sixth_month,
        borrower_payment_bandwidth,
        loan_status,
        loan_dbr,
        loan_credit_overdue_status,
        loan_localized_disbursement_date,
        loan_localized_expected_mature_date,
        loan_due_date,
        loan_incentive_amount,
        loan_ltv_verified,
        loan_ltv_self_declared,
        loan_dbr_verified,
        loan_self_declared_dbr,
        loan_dbr_status,
        loan_agreement_lender_platform_number,
        loan_agreement_borrower_lender_number,
        loan_requested_limit,
        loan_recommended_limit,
        loan_recommended_limit_after_survey,
        loan_limit,
        loan_interest,
        loan_tenure_months,
        loan_installment,
        first_purpose,
        second_purpose,
        third_purpose,
        property_localized_submission_date,
        property_estimated_price,
        property_verified_price,
        property_type,
        property_surface_area,
        property_building_area,
        property_certificate_type,
        property_certificate_owner,
        property_owner_presence_status,
        property_certificate_collateral_status,
        property_certificate_owner_presence_status,
        property_first_address,
        property_second_address,
        property_village_name,
        property_district_name,
        property_city_name,
        property_province_name,
        property_occupancy_status,
        property_occupants,
        criteria_active_from_timestamp,
        criteria_active_until_timestamp,
        opportunity_owner_email,
        opportunity_owner_role,
        business_platform,
        row_number() over (
            partition by
                im.loan_system_id,
                im.event_timestamp,
                im.event_name
            order by
                event_timestamp desc
        ) as rn
    from is_migration as im
    left join migrate_cohort as mc on im.borrower_phone_number = mc.borrower_phone_number
)

select
    loan_system_id,
    borrower_system_id,
    user_system_id,
    registration_date,
    prequal_submission_date,
    qualified_date,
    is_migration,
    event_timestamp,
    localized_event_date,
    event_name,
    group_status_name,
    platform_status_name,
    event_user_type,
    event_user_name,
    event_user_role,
    opportunity_owner_name,
    borrower_name,
    borrower_dob,
    borrower_pob,
    borrower_phone_number,
    borrower_email,
    borrower_marital_status,
    borrower_identity_number,
    borrower_gender,
    borrower_occupation,
    borrower_occupation_detail,
    borrower_verified_income,
    borrower_income_first_month,
    borrower_income_second_month,
    borrower_income_third_month,
    borrower_income_fourth_month,
    borrower_income_fifth_month,
    borrower_income_sixth_month,
    borrower_business_sector,
    borrower_business_address,
    borrower_verified_spouse_income,
    borrower_spouse_income_first_month,
    borrower_spouse_income_second_month,
    borrower_spouse_income_third_month,
    borrower_spouse_income_fourth_month,
    borrower_spouse_income_fifth_month,
    borrower_spouse_income_sixth_month,
    borrower_payment_bandwidth,
    loan_status,
    loan_dbr,
    loan_credit_overdue_status,
    loan_localized_disbursement_date,
    loan_localized_expected_mature_date,
    loan_due_date,
    loan_incentive_amount,
    loan_ltv_verified,
    loan_ltv_self_declared,
    loan_dbr_verified,
    loan_self_declared_dbr,
    loan_dbr_status,
    loan_agreement_lender_platform_number,
    loan_agreement_borrower_lender_number,
    loan_requested_limit,
    loan_recommended_limit,
    loan_recommended_limit_after_survey,
    loan_limit,
    loan_interest,
    loan_tenure_months,
    loan_installment,
    first_purpose,
    second_purpose,
    third_purpose,
    property_localized_submission_date,
    property_estimated_price,
    property_verified_price,
    property_type,
    property_surface_area,
    property_building_area,
    property_certificate_type,
    property_certificate_owner,
    property_owner_presence_status,
    property_certificate_collateral_status,
    property_certificate_owner_presence_status,
    property_first_address,
    property_second_address,
    property_village_name,
    property_district_name,
    property_city_name,
    property_province_name,
    property_occupancy_status,
    property_occupants,
    criteria_active_from_timestamp,
    criteria_active_until_timestamp,
    opportunity_owner_email,
    opportunity_owner_role,
    business_platform
from dedup_cohort
where
    rn = 1
    and not (
        is_migration = true
        and business_platform = 'infinid'
        and event_name in ('16_memo_shared_with_partner', '17_offer_waiting_for_offer', '22_sign_disbursed', 'lost_application_rejected', 'lost_sign_rejected', 'lost_application_canceled')
    )
